# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404-desktop"
  config.vm.box_check_update = false

  config.vm.synced_folder "..", "/genivi_swm"
  config.vm.synced_folder "../../rvi_sota_client", "/rvi_sota_client"

  config.vm.provision "file", source: "~/.Xauthority", destination: "/home/vagrant/.Xauthority"
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false, run: "always"

  config.vm.network :private_network, ip: "192.168.50.2"
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "genivi_swm"
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = false

    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--acpi", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
    ln -s /home/vagrant/.Xauthority /root
    ln -s /rvi_sota_client/run/sota_client /usr/bin/sota_client

    apt-get update && apt-get install -y \
      autoconf build-essential git httpie jq libfuse-dev liblz4-dev libtool \
      python-dbus python-gtk2 python-storm squashfs-tools

    git clone https://github.com/vasi/squashfuse
    cd squashfuse && ./autogen.sh && ./configure && make && make install
  SHELL
end
